version: '3.9'

# Development docker-compose for running all services at once
services:
  # Database service (CouchDB)
  db:
    extends:
      file: ./db/docker-compose.base.yml
      service: db-dev
    env_file:
      - ./db/.env
    volumes:
      - "./db/data:/opt/couchdb/data"
    ports:
      - "9002:5984"
    networks:
      - web

  # Backend service (FastAPI) with hot-reloading for development
  backend:
    extends:
      file: ./backend/docker-compose.base.yml
      service: backend-dev
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - "./backend:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web

  # Frontend service (React PWA) with hot-reloading for development
  web:
    extends:
      file: ./web/docker-compose.base.yml
      service: web-dev
    volumes:
      - "./web:/app"
    env_file:
      - ./web/.env
    depends_on:
      - backend
    networks:
      - web

networks:
  web:
    external: false
