services:
  db:
    container_name: budgeting_app__db
    extends:
      file: ./db/docker-compose.base.yml
      service: db-prod
    env_file:
      - ./db/.env
    volumes:
      - "./db/data:/opt/couchdb/data"
    expose:
      - "5984"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

  backend:
    container_name: budgeting_app__backend
    extends:
      file: ./backend/docker-compose.base.yml
      service: backend-prod
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - "./backend/data:/app/data"
      - "./backend/credentials:/app/credentials"
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

  web:
    container_name: budgeting_app__web
    extends:
      file: ./web/docker-compose.base.yml
      service: web-prod
    build:
      context: ./web
    env_file:
      - ./web/.env
    volumes:
      - "./web/build:/app/build"
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

networks:
  traefik:
    external: true
