version: '3.9'

# Root docker-compose for running all services at once
services:
  # Database service (CouchDB)
  db:
    extends:
      file: ./db/docker-compose.base.yml
      service: db-prod
    env_file:
      - ./db/.env
    volumes:
      - "./db/data:/opt/couchdb/data"
    ports:
      - "9002:5984"
    networks:
      - web

  # Backend service (FastAPI)
  backend:
    extends:
      file: ./backend/docker-compose.base.yml
      service: backend-prod
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - "./backend/data:/app/data"
      - "./backend/credentials:/app/credentials"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web

  # Frontend service (React PWA)
  web:
    extends:
      file: ./web/docker-compose.base.yml
      service: web-prod
    build:
      context: ./web
    env_file:
      - ./web/.env
    volumes:
      - "./web/build:/app/build"
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - web

networks:
  web:
    external: false
