# Base configurations for Backend component
x-backend-base: &backend-base
  container_name: budgeting_app__backend
  build: .
  env_file:
    - .env

# Production configuration
x-backend-prod: &backend-prod
  <<: *backend-base
  command: '/bin/bash -c "poetry run alembic upgrade head && poetry run uvicorn main:app --host=0.0.0.0 --port=8000"'
  volumes:
    - "./data:/app/data"
    - "./credentials:/app/credentials"
  networks:
    - traefik

# Development configuration
x-backend-dev: &backend-dev
  <<: *backend-base
  container_name: budgeting_app__backend__dev
  command: bash -c "poetry install && poetry run uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
  volumes:
    - ".:/app"
  ports:
    - "8000:8000"
  networks:
    - traefik

# Define actual services that can be extended
services:
  backend-prod:
    <<: *backend-prod
  backend-dev:
    <<: *backend-dev
