x-db-base: &db-base
  image: couchdb
  container_name: budgeting_app__db
  volumes:
    - "./data:/opt/couchdb/data"
    # Mount the custom startup script
    - "./start-and-configure.sh:/usr/local/bin/start-and-configure.sh"
    # Keep initdb.d in case other init scripts are needed
    - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  env_file:
    - .env
  # Override the entrypoint to use the custom script
  entrypoint: ["/usr/local/bin/start-and-configure.sh"]

# Production configuration
x-db-prod: &db-prod
  <<: *db-base
  networks:
    - traefik

# Development configuration
x-db-dev: &db-dev
  <<: *db-base
  container_name: budgeting_app__db__dev
  ports:
    - "9002:5984"

# Define actual services that can be extended
services:
  db-prod:
    <<: *db-prod
  db-dev:
    <<: *db-dev
