# Base configurations for Web component
x-web-base: &web-base
  container_name: budgeting_app__web
  build: .
  env_file:
    - .env

# Production configuration
x-web-prod: &web-prod
  <<: *web-base
  command: yarn run serve --single build --listen tcp://0.0.0.0:3000
  networks:
    - traefik

# Development configuration
x-web-dev: &web-dev
  image: node:20
  container_name: budgeting_app__web__dev
  working_dir: /app
  command: bash -c "yarn install && yarn start"
  volumes:
    - ".:/app"
  env_file:
    - .env
  environment:
    - WDS_SOCKET_PORT=3000
  ports:
    - "3000:3000"

# Define actual services that can be extended
services:
  web-prod:
    <<: *web-prod
  web-dev:
    <<: *web-dev
